### PR TITLE
Fixed Demo Issues

### PR DESCRIPTION
**Pull request by patocallaghan**
Changed demo to use 'match' signature

### CODE REVIEW

**Comment by mhulse** [comment]
We should merge this. Pat, don't you have the ability to merge this in?

**Comment by mhulse** [comment]
This is where I've got no experience. Stupid question: If we merge this fix, will #16 need to update their pull request with your changes before we merge their patch? I'd hate for your work to get stomped (or vice versa).

**Comment by mhulse** [comment]
I've looked over your changes and I feel like we can pull in this stuff no problems. If I don't hear from anyone by tomorrow, I'll go ahead and do the merge. After that, we can deal with #16. :+1: 

Thanks!

**Comment by patocallaghan** [comment]
Thanks for having a look at this @mhulse

**Comment by mhulse** [comment]
Awesome! Thanks Pat. :+1:

**Pull request merged**
