### PR TITLE
Added ability to fire callbacks on exiting breakpoints

### PR DESCRIPTION
**Pull request by patocallaghan**
Hey,

I really appreciate the work you've done with this plugin. Distinct from other plugins I like the fact you can define your breakpoints in one place, the CSS.

One feature I like from EnquireJS which you guys didn't have was the ability to fire callbacks when a breakpoint unmatches. For instance, a mobile menu may need different event listeners than a desktop view, so using `unmatch` you can unbind unneeded JS when you exit a breakpoint.

I"ve altered the `callbacks` key to use `match` and `unmatch` instead. I've also made sure this works for context ranges too so it will only trigger the match/unmatch when it moves from one range to another.

``` js
var queries = [
    {
        context: ['mobile', 'tablet'],
        call_for_each_context: false,
        match: function() {
            console.log('Bind Small!');
        },
        unmatch: function () {
            console.log('Unbind Small!');
        }
    },
    {
        context: ['desktop', 'widescreen'],
        call_for_each_context: false,
        match: function() {
            console.log('Bind Large!');
        },
        unmatch: function () {
            console.log('Unbind Large!');
        }
    },
    {
        context: 'mobile',
        match: function() {
            console.log('Bind Mobile!');
        },
        unmatch: function () {
            console.log('Unbind Mobile!');
        }
    },
    {
        context: 'tablet',
        match: function() {
            console.log('Bind Tablet!');
        },
        unmatch: function () {
            console.log('Unbind Tablet!');
        }
    },
    {
        context: 'desktop',
        match: function() {
            console.log('Bind Desktop!');
        },
        unmatch: function () {
            console.log('Unbind Desktop!');
        }
    },
    {
        context: 'widescreen',
        match: function() {
            console.log('Bind Widescreen!');
        },
        unmatch: function () {
            console.log('Unbind Widescreen!');
        }
    }
];
```

I"ve created a simple demo here if you want to have a gander at how it works:
http://codepen.io/patocallaghan/pen/jtDAL

I also added two convenience methods for getting the `this.context` and the `this.new_context` as these could be useful.

If you want me to re-jig or rewrite anything let me know.

Thanks,
Pat

### CODE REVIEW

**Comment by mhulse** [comment]
@patocallaghan:

Awesome additions. Thanks!

I could be wrong, but I think there's a bug with `MQ.addQuery`... Here's my [demo page](http://assets.registerguard.com/demos/aaa/).

[CSS here](http://assets.registerguard.com/demos/aaa/styles.css).

[JS here](http://assets.registerguard.com/demos/aaa/onmediaquery.js)

Visit the above HTML page, make the browser wide enough to hit the `tablet/desktop/widescreen` breakpoints, open FireBug and check the console, you'll probably see:

```
TypeError: query_object.callback is not a function
query_object.callback();
```

Looks like the offending line is:

`query_object.callback();`

Within the `addQuery` method.

I changed the above to `query_object.match();` and it seems to work better... What do you think of this change? I did not see any other spot where `callback()` was used, so I think the rest of the code is solid.

When you get a second, could you look this over? Does my proposed change seem like the way to go?

Thanks!
Micky

P.S. I could be wrong, but I noticed in your demo you did not test `addQuery` and `removeQuery` methods... Other than the above bug, do you think your code introduced any other bugs related to those API methods?

**Comment by mhulse** [comment]
FYI, [Here's the fix](https://github.com/registerguard/js-media-queries/blob/develop/onmediaquery/onmediaquery.js#L85-87) that I've applied to my `develop` branch.

Once we've nailed this down, I plan on doing cross-browser testing for my fork... I'm looking forward to using the new version! Thanks again for your hard work on this. :+1:

**Comment by patocallaghan** [comment]
Yep good catch, sorry about that....I've just tested the add and remove query api calls with your fix and it works....I'll add the fix to my pull request...

**Comment by mhulse** [comment]
Awesome! You rock! :)

**Comment by mhulse** [comment]
Btw, just a heads up, you might want to correct [this logic error](https://github.com/patocallaghan/js-media-queries/blob/0ad1ba3b5136e57d38db7f355ecabcea152eec6b/js/onmediaquery.js#L154); easily missed by a lint. I'd fixed that a while back on my fork, but forgot to give a heads up to Josh.

**Comment by JoshBarr** [comment]
That's really neat! We've often found ourselves writing the exit logic in other contexts, but doing so when leaving the target context makes much more sense and should make bugs easier to track down. Pulled into master!

**Pull request merged**
