### PR TITLE
I made a fix for older Firefox versions

### PR DESCRIPTION
**Pull request by Eworm**
getComputedStyle threw a javascript error in older versions of Firefox because the second parameter wasn't included. More info here: http://caniuse.com/#search=getComputedStyle. The fix doesn't seem to throw a new error in other browsers.

Signed-off-by: Wout Mager wout@woutmager.nl

### CODE REVIEW

**Comment by mhulse** [comment]
Looks like a decent patch.

Just did a quick Google to find:

> [Note: Prior to Gecko 2.0 (Firefox 4 / Thunderbird 3.3 / SeaMonkey 2.1), the pseudoElt parameter was required. No other major browser required this parameter be specified if null. Gecko has been changed to match the behavior of other browsers.](https://developer.mozilla.org/en-US/docs/DOM/window.getComputedStyle)

... and they have an example:

``` js
window.getComputedStyle(elem1, null);
```

It passes my sniff tests, though I typically like to cross-browser test the full suite of browsers when introducing a patch. On the other hand, this looks like a pretty benign patch.

Thoughts anyone?

I'll have some time to cross browser test this weekend using [browserstack.com](http://www.browserstack.com). Or, we could just pull it in and be done with it? :sailboat: 

@Eworm, did you happen to do any browser tests out side of older Firefox?

**Comment by Eworm** [comment]
I've tested this in the latest releases of Chrome & Firefox, as well as IE 8 & 9. They didn't throw any javascript errors. I would feel safer if this was tested by someone else too though. Just to be sure.

**Comment by mhulse** [comment]
@Eworm Thanks for reply and details. I agree with you about testing. I'll make the rounds through as many browsers as I can some time this week/weekend.

Good catch btw! It's always nice to make older browsers happy (I'm sure there's still a lot of folks using older FF's).

**Comment by Eworm** [comment]
Thanks! And apparently. Would be nice if this would fix it for them..

**Comment by mhulse** [comment]
@Eworm So, I did some tests on my fork, and based on my browserstack.com tests, it looks like Firefox 3.6 and above are happy. Just out of curiosity, how far back did you want to go in terms of older Firefox support? Version 3.6 and above seems pretty solid to me ... Just wondering what your expectations are. :)

**Comment by Eworm** [comment]
Well, the thing is, I discovered this fix because a client is still using FF3.5 internally. So egoistically speaking, up to 3.5 is fine with me. :)

**Comment by patocallaghan** [comment]
Thanks @Eworm. Unless we have any objections from @JoshBarr I don't see why we wouldn't pull this in...

**Comment by mhulse** [comment]
> Well, the thing is, I discovered this fix because a client is still using FF3.5 internally. So egoistically speaking, up to 3.5 is fine with me. :)

@eworm Ah, cool, I see now. Yah, browserstack.com (from what I saw) only had Firefox 3.0 and 3.6 (no 3.5). 3.6 worked without probs and the code failed in 3.0.

@patocallaghan I'd say let's pull 'er in!

**Comment by JoshBarr** [comment]
This sounds good to me - pull it in!

**Comment by Eworm** [comment]
Woohoo!

**Comment by mhulse** [comment]
Hehe! Ok, who's gonna be the first to the click the "Merge pull request" button? :dancers:

**Pull request merged**
